# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
 use_frameworks!
target 'RNMakkiiCore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for RNMakkiiCore
#  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#    'Core',
#    'CxxBridge', # Include this for RN >= 0.47
#    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
#    'RCTText',
#    'RCTNetwork',
#    'RCTWebSocket', # needed for debugging
#    # Add any other subspecs you want to use in your project
#  ]
#  # Explicitly include Yoga if you are using RN >= 0.42.0
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  # Third party deps podspec link
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'TrustWalletCore', :podspec=>'./TrustWalletCore.podspec'
 

end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.name == "React"
#      target.remove_from_project
#    end
#  end
#end
